### ISSUE TITLE
"payture.InPay is not a constructor"

### ISSUE THREAD

**Issue by yzalvov** [Payture/NodeJS-Payture-official#5]
`var inpay = new payture.InPay('https://sandbox.payture.com', { Key : 'YourMerchantAccount', Password : 'YourPassword' })` fails with the error. Real URL and Key provided to me are used, the Password is omitted though.

**Comment by sanyaches** [comment]
@yzalvov Try to delete `new` keyword, it'll work in this case. It's implemented by a function, returning `this`, without a constructor method.
